apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: httpd
    purpose: demo
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    app: httpd
  template:
    metadata:
      name: httpd
      labels:
        name: httpd
    spec:
      containers:
        - name: httpd1
          image: httpd
          ports:
            - containerPort: 80
              protocol: TCP